<?php
// $Id;

/**
 * @file
 *   OKHUB View Plugin default parameters.
 *
 */

//if (!defined('OKHUB_API_LIBRARY_PATH')) define('OKHUB_API_LIBRARY_PATH', 'okhubapi/');
if (!defined('OKHUB_API_ENVIRONMENT')) define('OKHUB_API_ENVIRONMENT', 'wordpress');

define('OKHUB_VIEW_MENU_TITLE', 'OKHUB View');

define('OKHUB_VIEW_DEFAULT_LANGUAGE', 'en');
define('OKHUB_VIEW_DISPLAY_ERRORS', TRUE);

/* Widget's default parameters */

define('OKHUB_VIEW_WIDGET_ASSETS_TYPE', 'documents');
define('OKHUB_VIEW_WIDGET_TITLE', 'OKHUB Updates');
define('OKHUB_VIEW_WIDGET_NUM_ITEMS', 10);



